[package]
name = "github-webhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
axum = ["dep:axum"]

[dependencies]
axum = { version = "0.6.12", optional = true }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
uuid = "1.3.0"
